// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"middle/internal/dao/internal"
	"middle/internal/model/entity"
)

// cmsAuthSsoDao is the data access object for the table cms_auth_sso.
// You can define custom methods on it to extend its functionality as needed.
type cmsAuthSsoDao struct {
	*internal.CmsAuthSsoDao
}

var (
	// CmsAuthSso is a globally accessible object for table cms_auth_sso operations.
	CmsAuthSso = cmsAuthSsoDao{internal.NewCmsAuthSsoDao()}
)

// Add your custom methods and functionality below.
func (m *cmsAuthSsoDao) GetRecordByAppID(ctx context.Context, appID string) (e *entity.CmsAuthSso, err error) {
	err = m.Ctx(ctx).Where("app_id=?", appID).Scan(&e)
	if err != nil {
		return nil, err
	}
	return e, nil
}
