// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"middle/internal/dao/internal"
	"middle/internal/model/entity"
)

// cmsUserDao is the data access object for the table cms_user.
// You can define custom methods on it to extend its functionality as needed.
type cmsUserDao struct {
	*internal.CmsUserDao
}

var (
	// CmsUser is a globally accessible object for table cms_user operations.
	CmsUser = cmsUserDao{internal.NewCmsUserDao()}
)

// Add your custom methods and functionality below.

func (m *cmsUserDao) GetRecordByFeishuCode(ctx context.Context, feishuCode string) (e *entity.CmsUser, err error) {
	err = m.Ctx(ctx).Where("feishu_code=?", feishuCode).Scan(&e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

func (m *cmsUserDao) GetRecordById(ctx context.Context, id uint) (e *entity.CmsUser, err error) {
	err = m.Ctx(ctx).Where("id=?", id).Scan(&e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

func (m *cmsUserDao) SaveRecord(ctx context.Context, e *entity.CmsUser) (lastId int64, err error) {
	return m.Ctx(ctx).OmitEmptyData().InsertAndGetId(e)
}
