// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"middle/internal/dao/internal"
)

// cmsRoleDao is the data access object for the table cms_role.
// You can define custom methods on it to extend its functionality as needed.
type cmsRoleDao struct {
	*internal.CmsRoleDao
}

var (
	// CmsRole is a globally accessible object for table cms_role operations.
	CmsRole = cmsRoleDao{internal.NewCmsRoleDao()}
)

// Add your custom methods and functionality below.
