// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"middle/internal/dao/internal"
)

// cmsRoleModuleDao is the data access object for the table cms_role_module.
// You can define custom methods on it to extend its functionality as needed.
type cmsRoleModuleDao struct {
	*internal.CmsRoleModuleDao
}

var (
	// CmsRoleModule is a globally accessible object for table cms_role_module operations.
	CmsRoleModule = cmsRoleModuleDao{internal.NewCmsRoleModuleDao()}
)

// Add your custom methods and functionality below.
