// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: api_auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginJumpUrlData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"jump_url" dc:"跳转地址"
	JumpUrl       string `protobuf:"bytes,1,opt,name=jump_url,json=jumpUrl,proto3" json:"jump_url" dc:"跳转地址"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginJumpUrlData) Reset() {
	*x = LoginJumpUrlData{}
	mi := &file_api_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginJumpUrlData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginJumpUrlData) ProtoMessage() {}

func (x *LoginJumpUrlData) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginJumpUrlData.ProtoReflect.Descriptor instead.
func (*LoginJumpUrlData) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginJumpUrlData) GetJumpUrl() string {
	if x != nil {
		return x.JumpUrl
	}
	return ""
}

type AuthSSOTokenData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"access_token" dc:"access_token"
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token" dc:"access_token"`
	// @inject_tag: json:"token_type" dc:"token_type"
	TokenType string `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type" dc:"token_type"`
	// @inject_tag: json:"expiry" dc:"过期到什么时间段"
	Expiry string `protobuf:"bytes,3,opt,name=expiry,proto3" json:"expiry" dc:"过期到什么时间段"`
	// @inject_tag: json:"expires_in" dc:"过期时间"
	ExpiresIn int32 `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in" dc:"过期时间"`
	// @inject_tag: json:"code" dc:"code"
	Code          int32 `protobuf:"varint,5,opt,name=code,proto3" json:"code" dc:"code"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSSOTokenData) Reset() {
	*x = AuthSSOTokenData{}
	mi := &file_api_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSSOTokenData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSSOTokenData) ProtoMessage() {}

func (x *AuthSSOTokenData) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSSOTokenData.ProtoReflect.Descriptor instead.
func (*AuthSSOTokenData) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthSSOTokenData) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthSSOTokenData) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *AuthSSOTokenData) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *AuthSSOTokenData) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *AuthSSOTokenData) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type AuthSSOUserinfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"uid" dc:"用户id"
	Uid int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid" dc:"用户id"`
	// @inject_tag: json:"name" dc:"用户名称"
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name" dc:"用户名称"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSSOUserinfo) Reset() {
	*x = AuthSSOUserinfo{}
	mi := &file_api_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSSOUserinfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSSOUserinfo) ProtoMessage() {}

func (x *AuthSSOUserinfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSSOUserinfo.ProtoReflect.Descriptor instead.
func (*AuthSSOUserinfo) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthSSOUserinfo) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AuthSSOUserinfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AuthSSOTokenFail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"code" dc:"code码"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" dc:"code码"`
	// @inject_tag: json:"error" dc:"描述"
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error" dc:"描述"`
	// @inject_tag: dc:"描述明细"
	ErrorDescription string `protobuf:"bytes,3,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty" dc:"描述明细"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthSSOTokenFail) Reset() {
	*x = AuthSSOTokenFail{}
	mi := &file_api_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSSOTokenFail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSSOTokenFail) ProtoMessage() {}

func (x *AuthSSOTokenFail) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSSOTokenFail.ProtoReflect.Descriptor instead.
func (*AuthSSOTokenFail) Descriptor() ([]byte, []int) {
	return file_api_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthSSOTokenFail) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuthSSOTokenFail) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AuthSSOTokenFail) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

var File_api_auth_proto protoreflect.FileDescriptor

const file_api_auth_proto_rawDesc = "" +
	"\n" +
	"\x0eapi_auth.proto\x12\x02pb\"-\n" +
	"\x10LoginJumpUrlData\x12\x19\n" +
	"\bjump_url\x18\x01 \x01(\tR\ajumpUrl\"\x9f\x01\n" +
	"\x10AuthSSOTokenData\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\tR\x06expiry\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x05R\texpiresIn\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x05R\x04code\"7\n" +
	"\x0fAuthSSOUserinfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x05R\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"i\n" +
	"\x10AuthSSOTokenFail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12+\n" +
	"\x11error_description\x18\x03 \x01(\tR\x10errorDescriptionB\aZ\x05../pbb\x06proto3"

var (
	file_api_auth_proto_rawDescOnce sync.Once
	file_api_auth_proto_rawDescData []byte
)

func file_api_auth_proto_rawDescGZIP() []byte {
	file_api_auth_proto_rawDescOnce.Do(func() {
		file_api_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_proto_rawDesc), len(file_api_auth_proto_rawDesc)))
	})
	return file_api_auth_proto_rawDescData
}

var file_api_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_auth_proto_goTypes = []any{
	(*LoginJumpUrlData)(nil), // 0: pb.LoginJumpUrlData
	(*AuthSSOTokenData)(nil), // 1: pb.AuthSSOTokenData
	(*AuthSSOUserinfo)(nil),  // 2: pb.AuthSSOUserinfo
	(*AuthSSOTokenFail)(nil), // 3: pb.AuthSSOTokenFail
}
var file_api_auth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_proto_init() }
func file_api_auth_proto_init() {
	if File_api_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_proto_rawDesc), len(file_api_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_auth_proto_goTypes,
		DependencyIndexes: file_api_auth_proto_depIdxs,
		MessageInfos:      file_api_auth_proto_msgTypes,
	}.Build()
	File_api_auth_proto = out.File
	file_api_auth_proto_goTypes = nil
	file_api_auth_proto_depIdxs = nil
}
